import type {
  NodeData,
  ConnectionTuple,
  BootLine,
  ProfileData,
} from "./types.js";

export const PROFILE: ProfileData = {
  name: "ILLIA KYSELOV",
  title: "Senior Frontend Engineer",
  tagline:
    "Product-oriented engineer building scalable frontends for high-traffic products.",
  location: "Kyiv, Ukraine",
  current: "Frontend Engineer @ Universe Group",
  email: "doncerber@gmail.com",
  linkedin: "https://www.linkedin.com/in/illiakyselov",
};

export const NODES: NodeData[] = [
  {
    id: "core",
    label: "CORE",
    sublabel: "IDENTITY",
    color: "#00ff88",
    position: [0, 0, 0],
    size: 2.0,
    content: {
      title: "Illia Kyselov",
      subtitle: "Senior Frontend Engineer",
      lines: [
        "Remote-first | Kyiv, Ukraine",
        "Currently @ Universe Group (Genesis Tech)",
        "Master's in CS @ Kyiv-Mohyla Academy",
        "",
        "Product-oriented engineer with 5+ years shipping Vue, Nuxt & React, Next and any frontend pokemon you can guess.",
        "Led frontend architecture for products reaching millions of users.",
        "Fullstack-capable when the project demands it.",
      ],
    },
  },
  {
    id: "experience",
    label: "EXP",
    sublabel: "5+ YEARS",
    color: "#00ccff",
    position: [-8, 3, -4],
    size: 1.6,
    content: {
      title: "Experience",
      subtitle: "5+ years building high-traffic products",
      lines: [
        "► UNIVERSE GROUP (Nov 2025 — Present)",
        "  Building frontend systems for high-scale products",
        "  across the Genesis Tech ecosystem.",
        "",
        "► SUBSUB (Jul 2024 — Nov 2025)",
        "  Solo frontend engineer. Owned frontend direction end-to-end.",
        "  Built 3 Nuxt applications from zero to production.",
        "  Migrated Laravel monolith → modular Vue SPA.",
        "  Established testing culture (unit + E2E) and led hiring.",
        "  Maintained zero production incidents during tenure.",
        "",
        "► NIMBLE CRM (Dec 2020 — Jul 2024)",
        "  Grew from junior to tech lead in 3.5 years.",
        "  Led refactor that reduced 2-5 recurring bugs/month.",
        "  Designed testing strategy (unit, component, E2E).",
        "  Drove React modernization initiative.",
      ],
    },
  },
  {
    id: "tech",
    label: "TECH",
    sublabel: "ARSENAL",
    color: "#cc44ff",
    position: [7, 4, -3],
    size: 1.5,
    content: {
      title: "Tech Arsenal",
      subtitle: "Core stack & capabilities",
      lines: [
        "► FRONTEND",
        "  Vue · Nuxt · React · Next.js · TypeScript · Tailwind CSS",
        "",
        "► TESTING",
        "  Vitest · Jest · Cypress · Testing Library",
        "",
        "► BACKEND",
        "  Laravel · Node.js · Python · Go",
        "",
        "► INFRASTRUCTURE",
        "  Cloudflare · Vite · Webpack",
        "",
        "► CREATIVE",
        "  Three.js · WebGL · GLSL Shaders",
        "  (this very site proves it)",
      ],
    },
  },
  {
    id: "education",
    label: "EDU",
    sublabel: "MASTERS",
    color: "#ff0088",
    position: [-6, -4, -2],
    size: 1.2,
    content: {
      title: "Education",
      subtitle: "Degrees & continuous learning",
      lines: [
        "► MASTER'S — Computer Science",
        "  Kyiv-Mohyla Academy (2025 — 2027)",
        "  In progress",
        "",
        "► BACHELOR'S — System Analysis",
        "  Kyiv National Economics University",
        "  (2021 — 2025)",
        "",
        "► CERTIFICATIONS",
        "  Real World Nuxt",
        "  API Design in Node.js v4",
        "  React Native v3",
        "  Complete Intro to Databases",
      ],
    },
  },
  {
    id: "philosophy",
    label: "CODE",
    sublabel: "PHILOSOPHY",
    color: "#ffcc00",
    position: [6, -3, -5],
    size: 1.3,
    content: {
      title: "Philosophy",
      subtitle: "How I think about code",
      lines: [
        "\"I don't chase hype. I choose tools",
        ' that fit the product, context, and team."',
        "",
        "► ARCHITECTURE FIRST",
        "  Every decision starts with structure.",
        "  Scalable, maintainable, debuggable.",
        "",
        "► ZERO EGO",
        "  No drama. Just clear decisions and solid execution.",
        "  The best code is the code the next engineer",
        "  doesn't need to rewrite.",
        "",
        "► SHIP WITH CONFIDENCE",
        "  Move fast, unblock teams, deliver.",
        "  Speed backed by tests, not luck.",
      ],
    },
  },
  {
    id: "contact",
    label: "LINK",
    sublabel: "CONTACT",
    color: "#00ffff",
    position: [0, -6, -3],
    size: 1.1,
    content: {
      title: "Contact",
      subtitle: "Let's connect",
      lines: [
        "► EMAIL",
        "  doncerber@gmail.com",
        "",
        "► LINKEDIN",
        "  linkedin.com/in/illiakyselov",
        "",
        "► LOCATION",
        "  Remote-first | Kyiv, Ukraine",
        "",
        "// Open to remote senior frontend & tech lead roles.",
        "// Product-oriented engineer, architecture-first delivery.",
      ],
    },
  },
];

export const CONNECTIONS: ConnectionTuple[] = [
  ["core", "experience"],
  ["core", "tech"],
  ["core", "education"],
  ["core", "philosophy"],
  ["core", "contact"],
  ["experience", "tech"],
  ["experience", "education"],
  ["tech", "philosophy"],
  ["education", "philosophy"],
  ["experience", "philosophy"],
  ["tech", "contact"],
  ["contact", "experience"],
];

export const BOOT_LINES: BootLine[] = [
  {
    time: 0,
    text: "> BIOS CHECK...",
    append: " OK",
    appendDelay: 300,
    color: "#00ff88",
  },
  { time: 400, text: "> GPU INITIALIZED: WebGL 2.0", color: "#00ff88" },
  { time: 700, text: "> LOADING NEURAL_MAP.dat...", color: "#00ff88" },
  { time: 900, text: "  ████████░░░░ 67%", color: "#00ccff" },
  { time: 1200, text: "  ████████████ 100%", color: "#00ccff" },
  { time: 1500, text: "> ACCESS LEVEL: VERIFIED", color: "#ff0088" },
  { time: 1800, text: "> SESSION: AUTHORIZED", color: "#00ccff" },
  { time: 2100, text: "> DECRYPTING PROFILE...", color: "#00ff88" },
  { time: 2400, text: "> SUBJECT: ILLIA KYSELOV", color: "#ffcc00" },
  { time: 2600, text: "> CLASS: SENIOR_FRONTEND_ENGINEER", color: "#ffcc00" },
  { time: 2900, text: "> SYSTEM_STATUS: READY", color: "#ff0088" },
  { time: 3300, text: "> ENTERING NEURAL INTERFACE...", color: "#cc44ff" },
  { time: 3700, text: "> ▶ ▶ ▶", color: "#00ff88" },
];
